### ISSUE TITLE
Tests fail after upgrade to PhantomJS 1.9.6 / GhostDriver 1.1.0

### ISSUE THREAD

**Issue by lfryc** [qa/arquillian-phantom-driver#10]
````
PhantomJS is launching GhostDriver...
[INFO  - 2014-01-24T10:11:03.778Z] GhostDriver - Main - running on port 21454
[ERROR - 2014-01-24T10:11:04.206Z] RouterReqHand - _handle.error - {"message":"Cannot find module 'cookiejar'","line":289,"sourceId":139708068089792,"sourceURL":"phantomjs://bootstrap.js","stack":"Error: Cannot find module 'cookiejar'\n    at phantomjs://bootstrap.js:289\n    at require (phantomjs://bootstrap.js:254)\n    at :/ghostdriver/session.js:104\n    at :/ghostdriver/request_handlers/session_manager_request_handler.js:75\n    at :/ghostdriver/request_handlers/session_maTests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.17 sec <<< FAILURE! - in org.jboss.arquillian.phantom.resolver.TestDriver
testSimpleWithPath(org.jboss.arquillian.phantom.resolver.TestDriver)  Time elapsed: 1.274 sec  <<< ERROR!
org.openqa.selenium.UnsupportedCommandException: Error - Cannot find module 'cookiejar'
Command duration or timeout: 679 milliseconds
Build info: version: '2.39.0', revision: '14fa800511cc5d66d426e08b0b2ab926c7ed7398', time: '2013-12-16 13:18:38'
System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.12.7-300.fc20.x86_64', java.version: '1.7.0_45'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:115)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:110)
	at org.jboss.arquillian.phantom.resolver.TestDriver.testSimpleWithPath(TestDriver.java:36)

testSimple(org.jboss.arquillian.phantom.resolver.TestDriver)  Time elapsed: 0.893 sec  <<< ERROR!
org.openqa.selenium.UnsupportedCommandException: Error - Cannot find module 'cookiejar'
Command duration or timeout: 515 milliseconds
Build info: version: '2.39.0', revision: '14fa800511cc5d66d426e08b0b2ab926c7ed7398', time: '2013-12-16 13:18:38'
System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.12.7-300.fc20.x86_64', java.version: '1.7.0_45'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:115)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:110)
	at org.jboss.arquillian.phantom.resolver.TestDriver.testSimple(TestDriver.java:21)

nager_request_handler.js:44\n    at :/ghostdriver/request_handlers/router_request_handler.js:70","stackArray":[{"sourceURL":"phantomjs://bootstrap.js","line":289},{"function":"require","sourceURL":"phantomjs://bootstrap.js","line":254},{"sourceURL":":/ghostdriver/session.js","line":104},{"sourceURL":":/ghostdriver/request_handlers/session_manager_request_handler.js","line":75},{"sourceURL":":/ghostdriver/request_handlers/session_manager_request_handler.js","line":44},{"sourceURL":":/ghostdriver/request_handlers/router_request_handler.js","line":70}]}
````

**Comment by smiklosovic** [comment]
I think this is not relevant anymore.
